// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uodukafjyzjcfrjnupvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVvZHVrYWZqeXpqY2Zyam51cHZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1Mzg2NzUsImV4cCI6MjA1MzExNDY3NX0.KVDFdr05V7PGDW_DK6Ndvu919zFXAZsgowuMb07cs1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);